// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvVjVReU5lMO5wwU_vwZfZvbYw3UPPfps',
    appId: '1:402155578:web:5defeed6430c30a92c2d03',
    messagingSenderId: '402155578',
    projectId: 'pennypal-featurenotbug',
    authDomain: 'pennypal-featurenotbug.firebaseapp.com',
    databaseURL: 'https://pennypal-featurenotbug-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pennypal-featurenotbug.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9NxaoHmqzSN6HmaxIQRuKd-wRTSEOM2s',
    appId: '1:402155578:android:162eb4197633ec332c2d03',
    messagingSenderId: '402155578',
    projectId: 'pennypal-featurenotbug',
    databaseURL: 'https://pennypal-featurenotbug-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pennypal-featurenotbug.firebasestorage.app',
  );
}
