// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0a-S1dbPvy0Y-uvN4AsYail_VFsLUOTM',
    appId: '1:760315859875:web:5c1f918120828da1688016',
    messagingSenderId: '760315859875',
    projectId: 'pennypal-featurenotbug-beb05',
    authDomain: 'pennypal-featurenotbug-beb05.firebaseapp.com',
    databaseURL: 'https://pennypal-featurenotbug-beb05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pennypal-featurenotbug-beb05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCEy5xT1ikJ-YtiEZMhrEikywUfafLiM',
    appId: '1:760315859875:android:4e44fa3f53ea12a9688016',
    messagingSenderId: '760315859875',
    projectId: 'pennypal-featurenotbug-beb05',
    databaseURL: 'https://pennypal-featurenotbug-beb05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pennypal-featurenotbug-beb05.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbfWsz3yHVFztWGNpngDUxQ-JVHn5zI_I',
    appId: '1:760315859875:ios:38160ba77e9f2fc2688016',
    messagingSenderId: '760315859875',
    projectId: 'pennypal-featurenotbug-beb05',
    databaseURL: 'https://pennypal-featurenotbug-beb05-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pennypal-featurenotbug-beb05.firebasestorage.app',
    iosBundleId: 'com.featurenotbug.pennypalStudent',
  );
}
